version: "3"
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "1234567q!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data_volume:/var/opt/mssql
    container_name: msql_db
volumes:
  sql_data_volume:
    
